export const marketIndexes = {
  KOSPI: { value: 3246.18, change: 0.42 },
  SPX: { value: 7575.39, change: 0.4 },
  IXIC: { value: 26281.61, change: 0.3 },
};

export const recommendations = [
  {
    ticker: "005930",
    name: "삼성전자",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "반도체",
    price: "82,400원",
    dayChange: 1.24,
    weekReturn: 4.1,
    monthReturn: 9.8,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "긍정",
    support: "79,500원",
    resistance: "86,000원",
    invalidate: "20일선 이탈",
    metrics: { momentum: 78, growth: 82, valuation: 64, quality: 72, liquidity: 92, sentiment: 74, risk: 58 },
    reasons: ["메모리 가격 회복과 HBM 수요 기대가 실적 추정치 개선으로 연결", "거래대금과 기관 순매수가 동시에 개선", "52주 고점 대비 부담이 크지 않은 구간"],
    risks: ["미국 기술주 변동성 확대", "원화 강세 시 수출주 마진 둔화"],
  },
  {
    ticker: "NVDA",
    name: "NVIDIA",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "AI 반도체",
    price: "$164.92",
    dayChange: 0.86,
    weekReturn: 3.4,
    monthReturn: 7.2,
    horizon: "long",
    horizonLabel: "장기",
    strength: "매우 긍정",
    support: "$151.00",
    resistance: "$178.00",
    invalidate: "60일선 하향 이탈",
    metrics: { momentum: 84, growth: 91, valuation: 48, quality: 89, liquidity: 96, sentiment: 82, risk: 62 },
    reasons: ["데이터센터 매출 성장률이 섹터 평균을 상회", "애널리스트 추정치 상향이 지속", "강한 유동성과 시장 주도주 프리미엄"],
    risks: ["고평가 부담", "수출 규제 및 공급망 리스크"],
  },
  {
    ticker: "TIGER200",
    name: "TIGER 200",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "국내 지수",
    price: "44,210원",
    dayChange: 0.33,
    weekReturn: 1.6,
    monthReturn: 4.4,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "42,900원",
    resistance: "45,500원",
    invalidate: "KOSPI 20일선 이탈",
    metrics: { momentum: 68, flow: 76, liquidity: 85, cost: 78, holdings: 71, risk: 54 },
    reasons: ["KOSPI 대형주 실적 회복 구간에 분산 노출", "거래대금과 AUM이 안정적", "개별 종목 위험을 낮추는 대안"],
    risks: ["반도체 비중 집중", "지수 급락 시 동반 하락"],
  },
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    exchange: "NYSE Arca",
    market: "US",
    assetType: "etf",
    sector: "미국 지수",
    price: "$621.30",
    dayChange: 0.28,
    weekReturn: 1.8,
    monthReturn: 5.1,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$603.00",
    resistance: "$638.00",
    invalidate: "월간 저점 이탈",
    metrics: { momentum: 74, flow: 82, liquidity: 98, cost: 77, holdings: 80, risk: 57 },
    reasons: ["미국 대형주 전반의 이익 추정치 개선", "ETF 자금 유입과 높은 유동성", "장기 포트폴리오 핵심 익스포저로 적합"],
    risks: ["빅테크 편중", "금리 재상승 시 멀티플 압박"],
  },
  {
    ticker: "035420",
    name: "NAVER",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "인터넷",
    price: "226,500원",
    dayChange: -0.18,
    weekReturn: 2.3,
    monthReturn: 6.7,
    horizon: "short",
    horizonLabel: "단기",
    strength: "관심",
    support: "214,000원",
    resistance: "238,000원",
    invalidate: "거래량 없는 반등",
    metrics: { momentum: 66, growth: 71, valuation: 69, quality: 67, liquidity: 76, sentiment: 65, risk: 53 },
    reasons: ["광고 경기 회복과 커머스 수익성 개선 기대", "낙폭 대비 반등 강도 개선", "밸류에이션 부담이 완화된 구간"],
    risks: ["플랫폼 규제", "AI 투자비 증가"],
  },
  {
    ticker: "000660",
    name: "SK하이닉스",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "반도체",
    price: "238,000원",
    dayChange: 1.08,
    weekReturn: 5.6,
    monthReturn: 12.2,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "매우 긍정",
    support: "224,000원",
    resistance: "252,000원",
    invalidate: "수급 급감",
    metrics: { momentum: 86, growth: 88, valuation: 57, quality: 76, liquidity: 91, sentiment: 81, risk: 61 },
    reasons: ["HBM 공급 기대와 이익 추정치 상향이 동반", "상대강도와 거래대금이 업종 내 우위", "외국인 수급 개선이 확인되는 구간"],
    risks: ["단기 급등 부담", "AI 반도체 투자 사이클 둔화 가능성"],
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "소프트웨어",
    price: "$506.18",
    dayChange: 0.41,
    weekReturn: 2.1,
    monthReturn: 5.9,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$486.00",
    resistance: "$525.00",
    invalidate: "클라우드 성장률 둔화",
    metrics: { momentum: 73, growth: 84, valuation: 55, quality: 92, liquidity: 95, sentiment: 76, risk: 49 },
    reasons: ["클라우드와 AI 소프트웨어 매출 가시성이 높음", "수익성과 현금흐름 품질이 우수", "대형 기술주 중 변동성 부담이 상대적으로 낮음"],
    risks: ["밸류에이션 부담", "AI 투자비 확대"],
  },
  {
    ticker: "AAPL",
    name: "Apple",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "하드웨어",
    price: "$226.40",
    dayChange: -0.12,
    weekReturn: 1.4,
    monthReturn: 4.8,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "$216.00",
    resistance: "$237.00",
    invalidate: "신제품 모멘텀 둔화",
    metrics: { momentum: 67, growth: 66, valuation: 58, quality: 88, liquidity: 94, sentiment: 68, risk: 47 },
    reasons: ["서비스 매출 안정성과 주주환원 기대", "대형주 방어 성격이 포트폴리오 변동성을 완화", "기술적 반등 구간 진입 가능성"],
    risks: ["중국 수요 둔화", "AI 기능 상용화 지연"],
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    exchange: "NASDAQ",
    market: "US",
    assetType: "etf",
    sector: "미국 성장주",
    price: "$542.12",
    dayChange: -0.22,
    weekReturn: 2.6,
    monthReturn: 6.3,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$519.00",
    resistance: "$561.00",
    invalidate: "NASDAQ 60일선 이탈",
    metrics: { momentum: 77, flow: 79, liquidity: 97, cost: 72, holdings: 84, risk: 60 },
    reasons: ["AI와 소프트웨어 대형주 강세에 직접 노출", "거래 유동성이 매우 높음", "중기 상대강도 우위"],
    risks: ["대형 기술주 집중", "변동성 확대"],
  },
  {
    ticker: "KODEX200",
    name: "KODEX 200",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "국내 지수",
    price: "44,180원",
    dayChange: 0.29,
    weekReturn: 1.5,
    monthReturn: 4.1,
    horizon: "long",
    horizonLabel: "장기",
    strength: "관심",
    support: "42,700원",
    resistance: "45,300원",
    invalidate: "지수 60일선 이탈",
    metrics: { momentum: 66, flow: 74, liquidity: 88, cost: 82, holdings: 70, risk: 52 },
    reasons: ["국내 대표지수에 낮은 비용으로 분산 투자", "거래 유동성과 추적 안정성이 양호", "대형주 실적 회복 국면에 활용 가능"],
    risks: ["반도체 비중 집중", "국내 증시 전반 조정"],
  },
  {
    ticker: "TIGERKR10",
    name: "TIGER 미국나스닥100",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "해외 성장주",
    price: "124,600원",
    dayChange: -0.15,
    weekReturn: 2.0,
    monthReturn: 5.8,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "119,500원",
    resistance: "129,000원",
    invalidate: "NASDAQ 추세 이탈",
    metrics: { momentum: 75, flow: 78, liquidity: 80, cost: 70, holdings: 83, risk: 59 },
    reasons: ["원화 계좌에서 미국 성장주 노출 가능", "NASDAQ 상대강도 개선", "AI 및 플랫폼 대형주 실적 모멘텀 반영"],
    risks: ["환율 변동", "빅테크 집중도"],
  },
  {
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    exchange: "NYSE Arca",
    market: "US",
    assetType: "etf",
    sector: "미국 중소형주",
    price: "$224.70",
    dayChange: 0.36,
    weekReturn: 1.9,
    monthReturn: 4.5,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "$214.00",
    resistance: "$235.00",
    invalidate: "금리 상승 재개",
    metrics: { momentum: 65, flow: 68, liquidity: 87, cost: 69, holdings: 62, risk: 64 },
    reasons: ["금리 안정 시 중소형주 상대매력 회복 가능", "대형 기술주 편중을 낮추는 보완 자산", "거래 유동성이 충분"],
    risks: ["경기 민감도", "대형주 대비 낮은 이익 가시성"],
  },
];

export const newsItems = [
  { source: "DART/KIND", summary: "반도체 대형주의 실적 전망 개선 공시와 업황 코멘트가 확인되었습니다.", url: "source: adapter://disclosures" },
  { source: "SEC EDGAR", summary: "미국 대형 기술주의 최신 분기 보고서와 리스크 요인을 요약 대상으로 등록했습니다.", url: "source: adapter://edgar" },
  { source: "FRED", summary: "미국 장기금리와 달러 지수 변화는 위험자산 선호도 판단에 반영됩니다.", url: "source: adapter://macro" },
];

export const calendarItems = [
  { date: "이번 주", title: "미국 CPI 및 소매판매", impact: "금리 민감 성장주 변동성 확대 가능" },
  { date: "이번 주", title: "한국 수출입 잠정치", impact: "반도체 및 자동차 업종 확인 필요" },
  { date: "다음 주", title: "미국 빅테크 실적", impact: "NASDAQ 및 QQQ 방향성 영향" },
];
