export const marketIndexes = {
  KOSPI: { value: 3246.18, change: 0.42 },
  SPX: { value: 7575.39, change: 0.4 },
  IXIC: { value: 26281.61, change: 0.3 },
};

export const recommendations = [
  {
    ticker: "005930",
    name: "삼성전자",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "반도체",
    price: "82,400원",
    dayChange: 1.24,
    weekReturn: 4.1,
    monthReturn: 9.8,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "긍정",
    support: "79,500원",
    resistance: "86,000원",
    invalidate: "20일선 이탈",
    metrics: { momentum: 78, growth: 82, valuation: 64, quality: 72, liquidity: 92, sentiment: 74, risk: 58 },
    reasons: ["메모리 가격 회복과 HBM 수요 기대가 실적 추정치 개선으로 연결", "거래대금과 기관 순매수가 동시에 개선", "52주 고점 대비 부담이 크지 않은 구간"],
    risks: ["미국 기술주 변동성 확대", "원화 강세 시 수출주 마진 둔화"],
  },
  {
    ticker: "NVDA",
    name: "NVIDIA",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "AI 반도체",
    price: "$164.92",
    dayChange: 0.86,
    weekReturn: 3.4,
    monthReturn: 7.2,
    horizon: "long",
    horizonLabel: "장기",
    strength: "매우 긍정",
    support: "$151.00",
    resistance: "$178.00",
    invalidate: "60일선 하향 이탈",
    metrics: { momentum: 84, growth: 91, valuation: 48, quality: 89, liquidity: 96, sentiment: 82, risk: 62 },
    reasons: ["데이터센터 매출 성장률이 섹터 평균을 상회", "애널리스트 추정치 상향이 지속", "강한 유동성과 시장 주도주 프리미엄"],
    risks: ["고평가 부담", "수출 규제 및 공급망 리스크"],
  },
  {
    ticker: "TIGER200",
    name: "TIGER 200",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "국내 지수",
    price: "44,210원",
    dayChange: 0.33,
    weekReturn: 1.6,
    monthReturn: 4.4,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "42,900원",
    resistance: "45,500원",
    invalidate: "KOSPI 20일선 이탈",
    metrics: { momentum: 68, flow: 76, liquidity: 85, cost: 78, holdings: 71, risk: 54 },
    reasons: ["KOSPI 대형주 실적 회복 구간에 분산 노출", "거래대금과 AUM이 안정적", "개별 종목 위험을 낮추는 대안"],
    risks: ["반도체 비중 집중", "지수 급락 시 동반 하락"],
  },
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    exchange: "NYSE Arca",
    market: "US",
    assetType: "etf",
    sector: "미국 지수",
    price: "$621.30",
    dayChange: 0.28,
    weekReturn: 1.8,
    monthReturn: 5.1,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$603.00",
    resistance: "$638.00",
    invalidate: "월간 저점 이탈",
    metrics: { momentum: 74, flow: 82, liquidity: 98, cost: 77, holdings: 80, risk: 57 },
    reasons: ["미국 대형주 전반의 이익 추정치 개선", "ETF 자금 유입과 높은 유동성", "장기 포트폴리오 핵심 익스포저로 적합"],
    risks: ["빅테크 편중", "금리 재상승 시 멀티플 압박"],
  },
  {
    ticker: "035420",
    name: "NAVER",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "인터넷",
    price: "226,500원",
    dayChange: -0.18,
    weekReturn: 2.3,
    monthReturn: 6.7,
    horizon: "short",
    horizonLabel: "단기",
    strength: "관심",
    support: "214,000원",
    resistance: "238,000원",
    invalidate: "거래량 없는 반등",
    metrics: { momentum: 66, growth: 71, valuation: 69, quality: 67, liquidity: 76, sentiment: 65, risk: 53 },
    reasons: ["광고 경기 회복과 커머스 수익성 개선 기대", "낙폭 대비 반등 강도 개선", "밸류에이션 부담이 완화된 구간"],
    risks: ["플랫폼 규제", "AI 투자비 증가"],
  },
  {
    ticker: "000660",
    name: "SK하이닉스",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "반도체",
    price: "238,000원",
    dayChange: 1.08,
    weekReturn: 5.6,
    monthReturn: 12.2,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "매우 긍정",
    support: "224,000원",
    resistance: "252,000원",
    invalidate: "수급 급감",
    metrics: { momentum: 86, growth: 88, valuation: 57, quality: 76, liquidity: 91, sentiment: 81, risk: 61 },
    reasons: ["HBM 공급 기대와 이익 추정치 상향이 동반", "상대강도와 거래대금이 업종 내 우위", "외국인 수급 개선이 확인되는 구간"],
    risks: ["단기 급등 부담", "AI 반도체 투자 사이클 둔화 가능성"],
  },
  {
    ticker: "005380",
    name: "현대차",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "자동차",
    price: "265,000원",
    dayChange: 0.42,
    weekReturn: 2.4,
    monthReturn: 5.8,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "긍정",
    support: "248,000원",
    resistance: "282,000원",
    invalidate: "60일선 이탈",
    metrics: { momentum: 72, growth: 78, valuation: 74, quality: 83, liquidity: 86, sentiment: 70, risk: 50 },
    reasons: ["완성차 수익성과 주주환원 기대가 동시에 반영", "최근 캔들 흐름에서 중기 추세 회복 확인", "밸류 부담이 대형 성장주 대비 낮은 편"],
    risks: ["환율 변동", "글로벌 자동차 수요 둔화"],
  },
  {
    ticker: "000270",
    name: "기아",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "자동차",
    price: "118,000원",
    dayChange: 0.36,
    weekReturn: 2.1,
    monthReturn: 5.1,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "긍정",
    support: "110,000원",
    resistance: "126,000원",
    invalidate: "거래량 동반 하락",
    metrics: { momentum: 70, growth: 76, valuation: 78, quality: 82, liquidity: 84, sentiment: 69, risk: 49 },
    reasons: ["높은 영업이익률과 배당 매력이 수익성 점수에 기여", "주봉 기준 저점이 높아지는 흐름", "현대차와 함께 자동차 업종 대표 후보"],
    risks: ["미국 판매 둔화", "원자재 비용 상승"],
  },
  {
    ticker: "207940",
    name: "삼성바이오로직스",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "바이오",
    price: "950,000원",
    dayChange: 0.22,
    weekReturn: 1.5,
    monthReturn: 4.2,
    horizon: "long",
    horizonLabel: "장기",
    strength: "관심",
    support: "905,000원",
    resistance: "990,000원",
    invalidate: "중기 추세선 이탈",
    metrics: { momentum: 65, growth: 80, valuation: 45, quality: 88, liquidity: 72, sentiment: 66, risk: 44 },
    reasons: ["CDMO 성장성과 이익 가시성이 높은 방어 성장주", "변동성 대비 추세 안정성이 양호", "바이오 섹터 내 대형 우량주 성격"],
    risks: ["밸류에이션 부담", "수주 공백 우려"],
  },
  {
    ticker: "068270",
    name: "셀트리온",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "바이오",
    price: "198,000원",
    dayChange: -0.12,
    weekReturn: 1.8,
    monthReturn: 3.9,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "188,000원",
    resistance: "210,000원",
    invalidate: "거래대금 감소",
    metrics: { momentum: 63, growth: 72, valuation: 58, quality: 74, liquidity: 78, sentiment: 63, risk: 52 },
    reasons: ["바이오시밀러 실적 회복 기대와 중기 반등 흐름", "낙폭 이후 변동성이 완화되는 구간", "거래대금이 유지되면 재평가 가능"],
    risks: ["약가 정책", "실적 확인 전 변동성"],
  },
  {
    ticker: "012450",
    name: "한화에어로스페이스",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "방산",
    price: "285,000원",
    dayChange: 0.88,
    weekReturn: 4.9,
    monthReturn: 10.4,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "매우 긍정",
    support: "264,000원",
    resistance: "304,000원",
    invalidate: "20일선 급락 이탈",
    metrics: { momentum: 84, growth: 86, valuation: 55, quality: 76, liquidity: 82, sentiment: 80, risk: 60 },
    reasons: ["수주 성장과 방산 수익성 개선 기대가 강함", "주봉 캔들 기준 추세 지속성이 높음", "거래량 동반 상승 구간에서 상대강도 우위"],
    risks: ["단기 급등 부담", "수주 뉴스 민감도"],
  },
  {
    ticker: "267260",
    name: "HD현대일렉트릭",
    exchange: "KRX",
    market: "KR",
    assetType: "stock",
    sector: "전력기기",
    price: "410,000원",
    dayChange: 1.12,
    weekReturn: 5.3,
    monthReturn: 13.7,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "매우 긍정",
    support: "382,000원",
    resistance: "438,000원",
    invalidate: "거래량 없는 고점 돌파 실패",
    metrics: { momentum: 88, growth: 89, valuation: 50, quality: 80, liquidity: 79, sentiment: 84, risk: 62 },
    reasons: ["전력기기 업황과 수익성 개선 기대가 강함", "캔들차트상 고점 갱신 흐름과 거래량이 동반", "3개월 수익률과 추세 품질이 높은 후보"],
    risks: ["고점권 변동성", "수주 피크아웃 우려"],
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "소프트웨어",
    price: "$506.18",
    dayChange: 0.41,
    weekReturn: 2.1,
    monthReturn: 5.9,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$486.00",
    resistance: "$525.00",
    invalidate: "클라우드 성장률 둔화",
    metrics: { momentum: 73, growth: 84, valuation: 55, quality: 92, liquidity: 95, sentiment: 76, risk: 49 },
    reasons: ["클라우드와 AI 소프트웨어 매출 가시성이 높음", "수익성과 현금흐름 품질이 우수", "대형 기술주 중 변동성 부담이 상대적으로 낮음"],
    risks: ["밸류에이션 부담", "AI 투자비 확대"],
  },
  {
    ticker: "AAPL",
    name: "Apple",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "하드웨어",
    price: "$226.40",
    dayChange: -0.12,
    weekReturn: 1.4,
    monthReturn: 4.8,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "$216.00",
    resistance: "$237.00",
    invalidate: "신제품 모멘텀 둔화",
    metrics: { momentum: 67, growth: 66, valuation: 58, quality: 88, liquidity: 94, sentiment: 68, risk: 47 },
    reasons: ["서비스 매출 안정성과 주주환원 기대", "대형주 방어 성격이 포트폴리오 변동성을 완화", "기술적 반등 구간 진입 가능성"],
    risks: ["중국 수요 둔화", "AI 기능 상용화 지연"],
  },
  {
    ticker: "GOOGL",
    name: "Alphabet",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "인터넷",
    price: "$178.40",
    dayChange: 0.31,
    weekReturn: 1.9,
    monthReturn: 4.6,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$169.00",
    resistance: "$188.00",
    invalidate: "광고 성장 둔화",
    metrics: { momentum: 70, growth: 80, valuation: 66, quality: 90, liquidity: 92, sentiment: 72, risk: 48 },
    reasons: ["검색 광고와 클라우드 수익성이 안정적", "대형 플랫폼 중 현금흐름 품질이 높음", "주봉 추세가 재개되면 TOP 후보로 부상 가능"],
    risks: ["반독점 규제", "AI 검색 경쟁"],
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "커머스/클라우드",
    price: "$215.30",
    dayChange: 0.52,
    weekReturn: 2.8,
    monthReturn: 6.9,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$202.00",
    resistance: "$228.00",
    invalidate: "AWS 성장률 둔화",
    metrics: { momentum: 76, growth: 86, valuation: 52, quality: 78, liquidity: 94, sentiment: 78, risk: 55 },
    reasons: ["AWS와 광고 사업 수익성 개선이 핵심", "최근 캔들상 중기 상승 추세 유지", "거래 유동성과 실적 모멘텀이 모두 양호"],
    risks: ["소비 둔화", "클라우드 경쟁 심화"],
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "플랫폼",
    price: "$610.20",
    dayChange: 0.44,
    weekReturn: 3.2,
    monthReturn: 8.5,
    horizon: "long",
    horizonLabel: "장기",
    strength: "매우 긍정",
    support: "$580.00",
    resistance: "$650.00",
    invalidate: "광고 단가 둔화",
    metrics: { momentum: 82, growth: 88, valuation: 58, quality: 87, liquidity: 91, sentiment: 83, risk: 54 },
    reasons: ["광고 수익성과 비용 효율화가 이익률을 지지", "3개월 추세와 수익성이 강한 후보", "AI 추천엔진 성과가 실적 모멘텀으로 연결"],
    risks: ["규제 리스크", "AI 인프라 투자비 증가"],
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "AI 반도체",
    price: "$275.10",
    dayChange: 0.76,
    weekReturn: 4.4,
    monthReturn: 11.2,
    horizon: "long",
    horizonLabel: "장기",
    strength: "매우 긍정",
    support: "$258.00",
    resistance: "$292.00",
    invalidate: "AI 반도체 추세 둔화",
    metrics: { momentum: 86, growth: 88, valuation: 50, quality: 84, liquidity: 88, sentiment: 84, risk: 58 },
    reasons: ["AI 네트워크 반도체 수요와 수익성 개선 기대", "주봉 캔들 기준 상승 추세가 강함", "수익률과 거래량이 함께 개선되는 구간"],
    risks: ["고평가 부담", "반도체 업황 변동성"],
  },
  {
    ticker: "AMD",
    name: "AMD",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "AI 반도체",
    price: "$176.80",
    dayChange: 1.05,
    weekReturn: 5.1,
    monthReturn: 12.4,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "긍정",
    support: "$162.00",
    resistance: "$190.00",
    invalidate: "거래량 동반 하락",
    metrics: { momentum: 84, growth: 80, valuation: 46, quality: 72, liquidity: 90, sentiment: 82, risk: 63 },
    reasons: ["AI 가속기 기대와 가격 모멘텀이 강함", "캔들차트상 반등 탄력이 큰 후보", "단기 수익률이 높아 TOP 순위 변동 가능성이 큼"],
    risks: ["변동성 확대", "실적 기대 미달"],
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    exchange: "NASDAQ",
    market: "US",
    assetType: "stock",
    sector: "전기차",
    price: "$318.60",
    dayChange: -0.38,
    weekReturn: 2.7,
    monthReturn: 9.1,
    horizon: "short",
    horizonLabel: "단기",
    strength: "관심",
    support: "$292.00",
    resistance: "$340.00",
    invalidate: "단기 추세선 이탈",
    metrics: { momentum: 78, growth: 65, valuation: 38, quality: 58, liquidity: 96, sentiment: 80, risk: 70 },
    reasons: ["단기 캔들 모멘텀은 강하지만 변동성도 큰 후보", "거래량이 동반될 때 순위가 빠르게 상승 가능", "수익성보다 추세 민감도가 큰 종목"],
    risks: ["가격 경쟁", "높은 변동성"],
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    exchange: "NYSE",
    market: "US",
    assetType: "stock",
    sector: "헬스케어",
    price: "$935.40",
    dayChange: 0.29,
    weekReturn: 1.8,
    monthReturn: 5.5,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$890.00",
    resistance: "$980.00",
    invalidate: "중기 저점 이탈",
    metrics: { momentum: 72, growth: 85, valuation: 42, quality: 86, liquidity: 82, sentiment: 75, risk: 45 },
    reasons: ["비만 치료제 성장성과 수익성이 장기 모멘텀", "변동성 대비 추세가 안정적인 방어 성장주", "헬스케어 내 대표 수익성 후보"],
    risks: ["밸류에이션 부담", "임상/규제 이벤트"],
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    exchange: "NYSE",
    market: "US",
    assetType: "stock",
    sector: "금융",
    price: "$238.90",
    dayChange: 0.18,
    weekReturn: 1.2,
    monthReturn: 3.6,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "$228.00",
    resistance: "$250.00",
    invalidate: "금융주 상대강도 둔화",
    metrics: { momentum: 64, growth: 70, valuation: 72, quality: 84, liquidity: 88, sentiment: 66, risk: 44 },
    reasons: ["수익성과 자본력이 안정적인 금융 대표주", "기술주 쏠림 완화 후보", "낮은 변동성과 현금흐름 안정성이 장점"],
    risks: ["금리 하락", "신용 리스크"],
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    exchange: "NASDAQ",
    market: "US",
    assetType: "etf",
    sector: "미국 성장주",
    price: "$542.12",
    dayChange: -0.22,
    weekReturn: 2.6,
    monthReturn: 6.3,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "$519.00",
    resistance: "$561.00",
    invalidate: "NASDAQ 60일선 이탈",
    metrics: { momentum: 77, flow: 79, liquidity: 97, cost: 72, holdings: 84, risk: 60 },
    reasons: ["AI와 소프트웨어 대형주 강세에 직접 노출", "거래 유동성이 매우 높음", "중기 상대강도 우위"],
    risks: ["대형 기술주 집중", "변동성 확대"],
  },
  {
    ticker: "KODEX200",
    name: "KODEX 200",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "국내 지수",
    price: "44,180원",
    dayChange: 0.29,
    weekReturn: 1.5,
    monthReturn: 4.1,
    horizon: "long",
    horizonLabel: "장기",
    strength: "관심",
    support: "42,700원",
    resistance: "45,300원",
    invalidate: "지수 60일선 이탈",
    metrics: { momentum: 66, flow: 74, liquidity: 88, cost: 82, holdings: 70, risk: 52 },
    reasons: ["국내 대표지수에 낮은 비용으로 분산 투자", "거래 유동성과 추적 안정성이 양호", "대형주 실적 회복 국면에 활용 가능"],
    risks: ["반도체 비중 집중", "국내 증시 전반 조정"],
  },
  {
    ticker: "TIGERKR10",
    name: "TIGER 미국나스닥100",
    exchange: "KRX",
    market: "KR",
    assetType: "etf",
    sector: "해외 성장주",
    price: "124,600원",
    dayChange: -0.15,
    weekReturn: 2.0,
    monthReturn: 5.8,
    horizon: "long",
    horizonLabel: "장기",
    strength: "긍정",
    support: "119,500원",
    resistance: "129,000원",
    invalidate: "NASDAQ 추세 이탈",
    metrics: { momentum: 75, flow: 78, liquidity: 80, cost: 70, holdings: 83, risk: 59 },
    reasons: ["원화 계좌에서 미국 성장주 노출 가능", "NASDAQ 상대강도 개선", "AI 및 플랫폼 대형주 실적 모멘텀 반영"],
    risks: ["환율 변동", "빅테크 집중도"],
  },
  {
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    exchange: "NYSE Arca",
    market: "US",
    assetType: "etf",
    sector: "미국 중소형주",
    price: "$224.70",
    dayChange: 0.36,
    weekReturn: 1.9,
    monthReturn: 4.5,
    horizon: "mid",
    horizonLabel: "중기",
    strength: "관심",
    support: "$214.00",
    resistance: "$235.00",
    invalidate: "금리 상승 재개",
    metrics: { momentum: 65, flow: 68, liquidity: 87, cost: 69, holdings: 62, risk: 64 },
    reasons: ["금리 안정 시 중소형주 상대매력 회복 가능", "대형 기술주 편중을 낮추는 보완 자산", "거래 유동성이 충분"],
    risks: ["경기 민감도", "대형주 대비 낮은 이익 가시성"],
  },
];

export const newsItems = [
  { source: "DART/KIND", summary: "반도체 대형주의 실적 전망 개선 공시와 업황 코멘트가 확인되었습니다.", url: "source: adapter://disclosures" },
  { source: "SEC EDGAR", summary: "미국 대형 기술주의 최신 분기 보고서와 리스크 요인을 요약 대상으로 등록했습니다.", url: "source: adapter://edgar" },
  { source: "FRED", summary: "미국 장기금리와 달러 지수 변화는 위험자산 선호도 판단에 반영됩니다.", url: "source: adapter://macro" },
];

export const calendarItems = [
  { date: "이번 주", title: "미국 CPI 및 소매판매", impact: "금리 민감 성장주 변동성 확대 가능" },
  { date: "이번 주", title: "한국 수출입 잠정치", impact: "반도체 및 자동차 업종 확인 필요" },
  { date: "다음 주", title: "미국 빅테크 실적", impact: "NASDAQ 및 QQQ 방향성 영향" },
];
